version = 0.1

[default.deploy.parameters]
stack_name = "chessU"
resolve_s3 = true
s3_prefix = "chessU"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CorsOrigin=\"http://chessu-alb-1491087100.us-east-1.elb.amazonaws.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
